const WORDS=WORD_TEXT.split('|').map((text,i)=>({id:i+1,text}));
const K='mm10_progress_v1';
const AB=[['rep','Repetición'],['del','Deletreo'],['cat','Categoría gramatical'],['cla','Clase según acento'],['sig','Acepción'],['seg','Seguridad oral']];
let P=JSON.parse(localStorage.getItem(K)||'{"w":{},"e":[],"s":[],"c":{}}');
let cur=2, oral=2, sim=null;
const $=id=>document.getElementById(id);
function save(){localStorage.setItem(K,JSON.stringify(P));dash()}
function today(){return new Date().toISOString().slice(0,10)}
function addDays(n){let d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
function st(id){return P.w[id]||(P.w[id]={state:'nueva',fail:0,att:0,a:{},next:today(),perfect:[]})}
function base(t){return t.split(',')[0].trim()}
function tit(s){return s.toLocaleLowerCase('es-EC').replace(/(^|\s|-)\p{L}/gu,m=>m.toLocaleUpperCase('es-EC'))}
function strip(s){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
function cat(t){let b=strip(base(t));if(/(ar|er|ir)$/.test(b))return'verbo';if(t.includes(',')||/(ico|ica|ivo|iva|oso|osa|al|ario|aria|ano|ana|eo|ea|ente|ble)$/.test(b))return'adjetivo';return'sustantivo'}
function risk(t){let r=[];if(/[ÁÉÍÓÚáéíóú]/.test(t))r.push('tilde');if(/[Hh]/.test(t))r.push('h');if(/[BVbv]/.test(t))r.push('b/v');if(/[CSZcsz]/.test(t))r.push('c/s/z');if(/[GJgj]/.test(t))r.push('g/j');if(/[Üü]/.test(t))r.push('diéresis');if(t.includes(','))r.push('género');return r.length?r:['deletreo']}
function W(id){let raw=WORDS[id-1].text,e=ENRICH[id]||{},c=P.c[id]||{};return{id,raw,base:tit(base(raw)),sil:c.sil||e.sil||'pendiente de confirmar',voc:c.voc||e.voc||((base(raw).match(/[ÁÉÍÓÚáéíóú]/)||['pendiente'])[0]).toLowerCase(),cla:c.cla||e.cla||(/[ÁÉÍÓÚáéíóú]/.test(raw)?'confirmar con sílabas':(/[aeiouns]$/i.test(strip(base(raw)))?'grave probable':'aguda probable')),cat:c.cat||e.cat||cat(raw),ace:c.ace||e.ace||['Acepción pendiente de completar con docente o diccionario.','Pista: identifica el área de la palabra y crea una frase.'],ej:c.ej||e.ej||'Crea una frase breve con esta palabra.',risk:risk(raw),letters:[...base(raw).toLowerCase()].join(' - ')} }
function chip(id){let x=st(id).state;let cls=x==='verde'?'green':x==='amarillo'?'yellow':x==='rojo'?'red':x==='negro'?'black':'';return `<span class="chip ${cls}">${x}</span>`}
function dash(){let v=WORDS.filter(x=>st(x.id).state==='verde').length,e=WORDS.filter(x=>['rojo','negro'].includes(st(x.id).state)).length,d=WORDS.filter(x=>st(x.id).next<=today()||['rojo','negro'].includes(st(x.id).state)).length;$('dashboard').innerHTML=`<div class="metric"><strong>500</strong><span>palabras oficiales</span></div><div class="metric"><strong>${v}</strong><span>dominadas</span></div><div class="metric"><strong>${e}</strong><span>en errores</span></div><div class="metric"><strong>${d}</strong><span>para hoy</span></div>`}
function speak(txt){if(!speechSynthesis)return alert('Este navegador no tiene voz.');speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(txt);u.lang='es-EC';u.rate=.86;speechSynthesis.speak(u)}
function preg(w){return`Número ${w.id}. La palabra es: ${w.base}. Ahora repite la palabra, deletrea y responde según el concurso.`}
function card(w){return`${chip(w.id)} <span class="chip">N.º ${w.id}</span><h2 class="word-title">${w.base}</h2><p><b>Audio de concurso:</b> “${preg(w)}”</p><p><b>Deletreo guía:</b> ${w.letters}</p><p><b>Sílabas:</b> ${w.sil}</p><p><b>Vocal tónica:</b> ${w.voc} · <b>Acento:</b> ${w.cla}</p><p><b>Categoría:</b> ${w.cat}</p><p><b>Acepciones:</b></p><ol>${w.ace.map(a=>`<li>${a}</li>`).join('')}</ol><p><b>Ejemplo:</b> ${w.ej}</p><p>${w.risk.map(r=>`<span class="chip red">${r}</span>`).join('')}</p>`}
function view(v){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===v));({apr,mem,oral:oralView,sim:simView,err,prog}[v])()}
function apr(){let w=W(cur);$('view').innerHTML=`<div class="grid"><div><h2>Modo aprender</h2><p class="small">Primero entiende la palabra; después la app te pregunta y te explica si fallas.</p><input id="q" class="input" placeholder="Buscar palabra o número" oninput="list(this.value)"><div id="list" class="list"></div></div><div class="card">${card(w)}<div class="controls"><button class="secondary" onclick="speak(preg(W(cur)))">▶ Escuchar palabra y consigna</button><button class="primary" onclick="oral=cur;view('oral')">Practicar como concurso</button><button onclick="cur=${w.id};memOne(${w.id})">Responder preguntas</button><button onclick="edit(${w.id})">Editar ficha</button></div></div></div>`;list('')}
function list(q=''){q=q.toLowerCase();let rows=WORDS.filter(w=>!q||String(w.id).includes(q)||w.text.toLowerCase().includes(q)).slice(0,100);$('list').innerHTML=rows.map(w=>`<div class="list-item"><span><b>${w.id}. ${tit(w.text)}</b> ${chip(w.id)}</span><button onclick="cur=${w.id};apr()">Ver</button></div>`).join('')}
function edit(id){let w=W(id);$('view').innerHTML=`<h2>Editar ficha: ${w.base}</h2><div class="notice">El PDF trae palabras, pero no definiciones. Completa acepciones verificadas por docente o diccionario.</div><div class="grid"><label>Sílabas<input id="sil" class="input" value="${w.sil}"></label><label>Vocal tónica<input id="voc" class="input" value="${w.voc}"></label><label>Acento<input id="cla" class="input" value="${w.cla}"></label><label>Categoría<input id="catx" class="input" value="${w.cat}"></label></div><label>Acepciones, una por línea<textarea id="ace">${w.ace.join('\n')}</textarea></label><label>Ejemplo<textarea id="ej">${w.ej}</textarea></label><button class="primary" onclick="saveEdit(${id})">Guardar</button> <button onclick="apr()">Volver</button>`}
function saveEdit(id){P.c[id]={sil:sil.value,voc:voc.value,cla:cla.value,cat:catx.value,ace:ace.value.split('\n').filter(Boolean),ej:ej.value};save();apr()}
function rnd(due=false){let pool=due?WORDS.filter(w=>st(w.id).next<=today()||['rojo','negro'].includes(st(w.id).state)):WORDS;if(!pool.length)pool=WORDS;return pool[Math.floor(Math.random()*pool.length)].id}
function rec(ab,f=1){let m={rep:'simulacro oral lento',del:'deletreo lento',cat:'tutor gramatical',cla:'clase según acento',sig:'modo acepciones y ejemplo',seg:'simulacro suave'};return(f>=3?'Palabra crítica. ':'Vuelta recomendada: ')+(m[ab]||'repasar')}
function grade(id,ab,ok,res='',cor=''){let x=st(id);x.att++;x.a[ab]=x.a[ab]||{ok:0,bad:0};if(ok){x.a[ab].ok++;x.state=x.state==='verde'?'verde':'amarillo';x.next=addDays(3)}else{x.a[ab].bad++;x.fail++;x.state=x.fail>=3?'negro':'rojo';x.next=today();P.e.unshift({date:new Date().toISOString(),id,word:W(id).base,ab,label:(AB.find(a=>a[0]===ab)||[])[1]||ab,res,cor,rec:rec(ab,x.fail)})}save()}
function soc(ab,w){let q={del:[`Mira la parte riesgosa: ${w.risk.join(', ')}.`,`Divide la palabra en sílabas antes de deletrear.`,`Ahora di una letra por vez sin correr.`],cat:[`Pregúntate: ¿nombra una cosa, describe una cualidad o expresa una acción?`,`Prueba con artículo: el/la ${w.base.toLowerCase()}.`,`Si nombra algo y acepta artículo, normalmente es sustantivo.`],cla:[`Escucha la fuerza de voz: ${w.base}.`,`Ubica si la fuerza está en la última, penúltima o antepenúltima sílaba.`,`Recuerda: las esdrújulas siempre se tildan.`],sig:[`Identifica el área de la palabra: ciencia, literatura, geografía, historia o uso general.`,`Descarta las opciones que no tengan relación.`,`Crea una frase corta para comprobar el significado.`],seg:['Respira antes de responder.','Sigue el orden oficial: repetir, deletrear, clasificar, definir.']};return q[ab]||['Piensa la pista.','Descarta lo imposible.']}
function why(ab,chosen,cor,w,ok){let title=ok?'✅ Correcto':'🔎 Revisemos con calma';let rule={cla:`Respuesta correcta: <b>${cor}</b>. Para decidirlo, primero ubica la sílaba con más fuerza de voz.`,cat:`Respuesta correcta: <b>${cor}</b>. Pregunta clave: ¿la palabra nombra algo, describe algo o expresa una acción?`,sig:`Respuesta correcta: <b>${cor}</b>. Una acepción debe coincidir con el uso real de la palabra y con su categoría.`,del:`Guía de deletreo: <b>${w.letters}</b>. Observa las letras de riesgo: ${w.risk.join(', ')}.`}[ab]||`Respuesta correcta: <b>${cor}</b>.`;
return `<div class="notice"><h3>${title}</h3><p><b>Tu respuesta:</b> ${chosen}</p><p>${rule}</p><p><b>Tutor socrático:</b></p><ol>${soc(ab,w).map(x=>`<li>${x}</li>`).join('')}</ol><p><b>Vuelta recomendada:</b> ${ok?'repasar en otra sesión para fijar memoria.':rec(ab,st(w.id).fail)}</p></div>`}
function ans(id,ab,chosen,cor){let w=W(id);let ok=strip(chosen)===strip(cor)||strip(cor).includes(strip(chosen))||strip(chosen).includes(strip(cor));grade(id,ab,ok,chosen,cor);let fb=$('feedback');if(fb)fb.innerHTML=why(ab,chosen,cor,w,ok);document.querySelectorAll(`[data-ab="${ab}"]`).forEach(b=>{b.disabled=true;if(strip(b.textContent)===strip(cor))b.classList.add('ok');else if(strip(b.textContent)===strip(chosen))b.classList.add('danger')})}
function opt(arr,ab,cor,id){let opts=[...new Set([cor,...arr].filter(Boolean))].slice(0,5).sort(()=>Math.random()-.5);return opts.map(x=>`<button data-ab="${ab}" onclick="ans(${id},'${ab}',this.textContent,'${cor.replace(/'/g,"&#39;")}')">${x}</button>`).join('')}
function mem(){memOne(rnd(true))}
function memOne(id){let w=W(id);cur=w.id;let dist=['Instrumento de medición.','Figura geométrica.','Proceso histórico.','Parte de una célula.'];$('view').innerHTML=`<h2>Modo memorizar con tutor</h2><div class="notice"><b>Escucha, responde y revisa.</b> Si fallas, la app no solo marca error: te hace razonar el porqué.</div><div class="card">${card(w)}<div class="controls"><button class="secondary" onclick="speak(preg(W(cur)))">▶ Escuchar palabra y consigna</button><button onclick="mem()">Otra palabra</button></div></div><div class="grid-3"><div class="card"><h3>1. Clase según acento</h3>${opt(['aguda','grave','esdrújula','sobresdrújula'], 'cla', w.cla, w.id)}</div><div class="card"><h3>2. Categoría gramatical</h3>${opt(['sustantivo','adjetivo','verbo','adverbio','adjetivo/sustantivo'], 'cat', w.cat, w.id)}</div><div class="card"><h3>3. Acepción correcta</h3>${opt([w.ace[0],...dist].slice(0,4),'sig',w.ace[0],w.id)}</div></div><div id="feedback"></div>`}
const STEPS=[['rep','Repetir palabra'],['del','Deletrear'],['cat','Categoría gramatical'],['cla','Clase según acento'],['sig','Acepción correcta']];
function hint(ab,w){return{rep:'Repetir exactamente la palabra escuchada.',del:w.letters,cat:w.cat,cla:w.cla,sig:w.ace[0]}[ab]||''}
function oralView(){let w=W(oral);$('view').innerHTML=`<h2>Práctica oral tipo concurso</h2><div class="grid"><div class="card">${card(w)}<div class="controls"><button class="secondary" onclick="speak(preg(W(oral)))">▶ Escuchar palabra y consigna</button><button onclick="oral=rnd();oralView()">Aleatoria</button></div><input id="num" class="input" type="number" min="1" max="500" placeholder="Número 1-500"><button onclick="if(num.value>=1&&num.value<=500){oral=+num.value;oralView()}">Ir al número</button></div><div>${STEPS.map(([ab,l])=>`<div class="card"><h3>${l}</h3><p><b>Guía para el adulto:</b> ${hint(ab,w)}</p><button class="ok" onclick="grade(${w.id},'${ab}',true);this.parentElement.querySelector('.feed').innerHTML=why('${ab}','Correcto','${hint(ab,w).replace(/'/g,"&#39;")}',W(${w.id}),true)">Correcto</button> <button class="danger" onclick="grade(${w.id},'${ab}',false,'oral','${hint(ab,w).replace(/'/g,"&#39;")}');this.parentElement.querySelector('.feed').innerHTML=why('${ab}','Incorrecto','${hint(ab,w).replace(/'/g,"&#39;")}',W(${w.id}),false)">Necesita otra vuelta</button><details open><summary>Preguntas del tutor socrático</summary><ol>${soc(ab,w).map(x=>`<li>${x}</li>`).join('')}</ol></details><div class="feed"></div></div>`).join('')}<button class="primary" onclick="perfect(${w.id})">Cerrar palabra y pasar a otra</button></div></div>`}
function perfect(id){let x=st(id),d=today();if(!x.perfect.includes(d))x.perfect.push(d);x.state=x.perfect.length>=2?'verde':'amarillo';x.next=addDays(x.state==='verde'?7:3);save();oral=rnd(true);oralView()}
function simView(){if(!sim)sim={ids:Array.from({length:5},()=>rnd()),i:0,score:0,res:[]};let w=W(sim.ids[sim.i]);$('view').innerHTML=`<h2>Simulacro de 5 rondas</h2><div class="bar"><span style="width:${sim.i*20}%"></span></div><p><b>Ronda ${sim.i+1}/5</b> Puntaje: ${sim.score}/25</p><div class="grid"><div class="card">${card(w)}<button class="secondary" onclick="speak(preg(W(${w.id})))">▶ Escuchar palabra y consigna</button></div><div class="card">${STEPS.map(([ab,l])=>`<label><input type="checkbox" data-ab="${ab}"> ${l}</label><br>`).join('')}<button class="primary" onclick="nextSim(${w.id})">Siguiente</button></div></div>`}
function nextSim(id){let pts=0;document.querySelectorAll('[data-ab]').forEach(c=>{if(c.checked)pts++;grade(id,c.dataset.ab,c.checked)});sim.score+=pts;sim.res.push([id,pts]);sim.i++;if(sim.i>=5){P.s.unshift({date:new Date().toISOString(),score:sim.score,res:sim.res,weak:weak()});let sc=sim.score;sim=null;save();$('view').innerHTML=`<h2>Simulacro terminado</h2><p class="word-title">${sc}/25</p><p>${rec(weak())}</p><button onclick="simView()">Nuevo</button><button onclick="view('err')">Errores</button>`}else simView()}
function weak(){let o={};P.e.forEach(e=>o[e.ab]=(o[e.ab]||0)+1);return Object.entries(o).sort((a,b)=>b[1]-a[1])[0]?.[0]||'sig'}
function err(){$('view').innerHTML=`<h2>Banco de errores</h2><div class="notice">Cada error se guarda por habilidad y genera una vuelta recomendada.</div><button class="primary" onclick="oral=(P.e[0]?.id||rnd(true));view('oral')">Qué debo practicar ahora</button><div class="list">${P.e.slice(0,150).map(e=>`<div class="list-item"><span><b>${e.word}</b> ${chip(e.id)}<br>${new Date(e.date).toLocaleString()} · ${e.label}<br>${e.rec}</span><button onclick="oral=${e.id};view('oral')">Practicar</button></div>`).join('')||'Sin errores aún.'}</div>`}
function prog(){let stats=AB.map(([k,l])=>{let ok=0,bad=0;Object.values(P.w).forEach(w=>{if(w.a?.[k]){ok+=w.a[k].ok;bad+=w.a[k].bad}});let pct=ok+bad?Math.round(ok/(ok+bad)*100):0;return`<div class="card"><b>${l}</b><p class="word-title">${pct}%</p><small>${ok} aciertos · ${bad} errores</small></div>`}).join('');$('view').innerHTML=`<h2>Progreso</h2><div class="grid-3">${stats}</div><h3>Simulacros</h3><div class="list">${P.s.slice(0,10).map(s=>`<div class="list-item"><span>${new Date(s.date).toLocaleString()} · ${s.score}/25 · reforzar ${s.weak}</span></div>`).join('')||'Sin simulacros.'}</div><textarea readonly>${JSON.stringify(P,null,2)}</textarea><button class="danger" onclick="if(confirm('¿Borrar progreso?')){P={w:{},e:[],s:[],c:{}};save();prog()}">Borrar progreso</button>`}
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(console.warn));
dash();apr();
